kind: Service
apiVersion: v1
metadata:
  labels:
    app: system-update-page
  name: system-update-page
  namespace: dev
spec:
  ports:
  - name: sup
    port: 80
    targetPort: 80
  selector:
    app: system-update-page

