kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
  namespace: staging
rules:
- apiGroups:
  - extensions
  - ""
  resources:
  - pods
  - deployments
  - deployments/rollback
  - rollouts
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - post
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
  namespace: staging
subjects:
  - kind: User
    name: jenkins@informationtechnology-205813.iam.gserviceaccount.com
    namespace: staging
roleRef:
  kind: Role
  name: jenkins
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
  namespace: staging
rules:
- apiGroups:
  - extensions
  - ""
  resources:
  - pods
  - deployments
  - deployments/rollback
  - rollouts
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - post
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jenkins
  namespace: staging
subjects:
  - kind: User
    name: jenkins@informationtechnology-205813.iam.gserviceaccount.com
    namespace: staging
roleRef:
  kind: Role
  name: jenkins
  apiGroup: rbac.authorization.k8s.io
